// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/register" | "/dashboard";
  };
  "./routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/";
  };
  "./routes/auth/layout.tsx": {
    id: "routes/auth/layout";
    page: "/register";
  };
  "./routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/register";
  };
  "./routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
};